<?php

namespace Tests\Integration;

use App\Modulos\RedmineMantencion\Services\MantencionEstadisticasService;
use App\Services\Database\SchemaBaseline;
use Illuminate\Database\Events\QueryExecuted;
use Illuminate\Events\Dispatcher;
use Illuminate\Support\Facades\DB;
use PHPUnit\Framework\Attributes\PreserveGlobalState;
use PHPUnit\Framework\Attributes\RunTestsInSeparateProcesses;

#[RunTestsInSeparateProcesses]
#[PreserveGlobalState(false)]
final class MantencionStatisticsReadQueryTest extends IsolatedMariaDbTestCase
{
    protected function setUp(): void
    {
        parent::setUp();
        // Load actual pure helpers and DB factories, without legacy bootstrap,
        // sessions, production configuration, logging or external services.
        $source = file_get_contents(dirname(__DIR__, 2).'/RedmineMantencion/controllers/dashboard.php');
        foreach (['dashboard_expand_message', 'dashboard_repair_structure_encoding', 'dashboard_fix_text_encoding',
            'dashboard_core_parse_datetime', 'dashboard_normalize_phone', 'dashboard_core_build_subject',
            'dashboard_core_build_description', 'dashboard_resolve_department_value', 'dashboard_resolve_unit_value',
            'dashboard_core_resolve_category', 'dashboard_catalog_names', 'dashboard_normalize_email', 'load_messages'] as $name) {
            $start = strpos($source, 'function '.$name.'(');
            $end = strpos($source, "\n}", $start) + 2;
            eval(substr($source, $start, $end - $start));
        }
        $source = file_get_contents(dirname(__DIR__, 2).'/RedmineMantencion/controllers/storage.php');
        foreach (['mantencion_report_repository', 'mantencion_hours_extra_repository', 'mantencion_catalog_repository'] as $name) {
            $start = strpos($source, 'function '.$name.'(');
            $end = strpos($source, "\n    }", $start) + 6;
            eval(substr($source, $start, $end - $start));
        }
        $schema = new SchemaBaseline;
        $schema->bootstrap(DB::connection(), $schema->read(dirname(__DIR__, 2).'/database/baselines/2026-09-15'));
        DB::table('modulos_nova')->insert([
            ['id' => 1, 'clave_modulo' => 'redmine_tic', 'nombre' => 'TIC'],
            ['id' => 2, 'clave_modulo' => 'redmine-mantencion', 'nombre' => 'Mantención'],
        ]);
        foreach (['Red', 'Réd', '0101', '0', ' ELÉCTRICA ', 'ElectrÃ³nica'] as $i => $name) {
            DB::table('categorias')->insert(['id' => $i + 1, 'nombre' => $name]);
        }
        DB::table('horas_extra_grupos')->insert([
            ['id' => 1, 'fecha' => '2026-09-01'], ['id' => 2, 'fecha' => '2024-01-01'],
            ['id' => 3, 'fecha' => '2026-09-01'],
        ]);
        for ($id = 1; $id <= 90; $id++) {
            DB::table('redmine_mantencion_reportes')->insert([
                'id' => $id, 'modulo_id' => $id % 13 ? 2 : 1,
                'fuente' => ['core', 'manual', 'otro', ' CORE '][$id % 4],
                'fuente_id' => $id % 6 ? 'message-'.$id : 'repeated',
                'estado' => $id === 13 ? 'archivado' : ['archivado', 'pendiente', 'procesado', 'error', 'procesada', null, ' ARCHIVADO '][$id % 7],
                'asunto' => 'Asunto '.$id, 'descripcion' => 'Descripción '.$id,
                'categoria_id' => $id % 8 === 0 ? null : 1 + $id % 6,
                'id_redmine_asignado' => ['101', '0101', '202', '', null, ' 101 '][$id % 6],
                'asignado_nombre' => ['Persona Uno', 'Pérez', 'PÃ©rez', '', '0', '101'][$id % 6],
                'unidad_texto' => ['Red', ' Réd ', 'N/A', '', '0', '0101'][$id % 6],
                'fecha_reporte' => '2026-09-'.str_pad((string) (1 + $id % 3), 2, '0', STR_PAD_LEFT),
                'fecha_inicio' => '2024-01-01', 'fecha_fin' => '2027-01-01', 'hora_reporte' => '18:30:00',
                'hora_extra' => $id % 2, 'numero_ticket_redmine' => $id + 100,
                'actualizado_at' => '2026-09-15 12:00:00',
            ]);
            if ($id % 3 === 0 || $id === 13) {
                foreach ([1, 2, 3] as $group) {
                    DB::table('horas_extra_grupo_reportes')->insert(['grupo_id' => $group, 'origen' => 'mantencion', 'reporte_id' => $id]);
                }
            }
            DB::table('horas_extra_grupo_reportes')->insert(['grupo_id' => 1, 'origen' => 'tic', 'reporte_id' => $id]);
        }
    }

    private function reference(array $filters): array
    {
        $read = require __DIR__.'/fixtures/mantencion_statistics_reference.php';

        return $read->call(new MantencionEstadisticasService, $filters);
    }

    private function comparable(array $stats): array
    {
        // Wall-clock refresh label is generated by both readers, independently.
        unset($stats['actualizado']);

        return $stats;
    }

    public function test_three_sources_preserve_filters_repetition_order_and_all_message_fields(): void
    {
        $service = new MantencionEstadisticasService;
        $filters = [[], ['desde' => '2026-09-02'], ['hasta' => '2026-09-02'],
            ['desde' => '2026-09-03', 'hasta' => '2026-09-01'], ['desde' => 'invalid'],
            ['desde' => '2030-01-01'], ['categoria' => 'red'], ['categoria' => 'réd'],
            ['categoria' => 'ELÉCTRICA'], ['categoria' => 'eléctrica'], ['categoria' => 'Modificar Perfil CORE'],
            ['categoria' => '0'], ['unidad' => 'Red'], ['unidad' => 'N/A'], ['unidad' => '0'],
            ['usuario' => '101'], ['usuario' => '0101'], ['usuario' => '202'], ['usuario' => 'Pérez'],
            ['usuario' => 'PÃ©rez'], ['usuario' => '0'], ['usuario' => 'missing'],
            ['desde' => '2026-09-01', 'hasta' => '2026-09-03', 'usuario' => '101', 'categoria' => 'Red']];
        foreach ($filters as $filter) {
            self::assertSame($this->comparable($this->reference($filter)), $this->comparable($service->statisticsForFilters($filter)));
        }
        $rows = array_merge(...array_values($service->statisticsForFilters([])['msgs_por_usuario']));
        $sources = array_count_values(array_column($rows, '_fuente'));
        self::assertGreaterThan(0, $sources['mensajes']);
        self::assertGreaterThan(0, $sources['reportes']);
        self::assertGreaterThan(0, $sources['horas_extra']);
        $foreign = array_values(array_filter($rows, fn ($r) => $r['id'] === 'message-13'));
        self::assertCount(3, $foreign, 'The existing hours reader includes linked archived rows without a module predicate.');
        self::assertSame(['horas_extra'], array_values(array_unique(array_column($foreign, '_fuente'))));
        self::assertGreaterThan(count(array_unique(array_column($rows, 'id'))), count($rows), 'Repeated source/hour contributions are intentionally retained.');
        self::assertCount(0, array_filter($rows, fn ($r) => array_key_exists('_statistics_id', $r)));
        foreach ($rows as $row) {
            self::assertArrayHasKey('descripcion', $row);
            self::assertArrayHasKey('numero_ticket_redmine', $row);
        }
    }

    public function test_zero_dates_missing_dates_bigint_and_duplicate_public_ids_keep_current_rules(): void
    {
        $mode = DB::selectOne('SELECT @@SESSION.sql_mode AS mode')->mode;
        try {
            DB::statement("SET SESSION sql_mode = ''");
            $seed = (array) DB::table('redmine_mantencion_reportes')->where('id', 7)->first();
            foreach (['9223372036854775807', '9223372036854775808'] as $id) {
                DB::table('redmine_mantencion_reportes')->insert(array_replace($seed, ['id' => $id,
                    'fuente' => 'manual', 'fuente_id' => '0', 'fecha_reporte' => '2026-00-00']));
                DB::table('horas_extra_grupo_reportes')->insert(['grupo_id' => 1, 'origen' => 'mantencion', 'reporte_id' => $id]);
            }
            DB::table('redmine_mantencion_reportes')->whereIn('id', [1, 2, 3, 4])->update(['fecha_reporte' => null]);
        } finally {
            DB::statement('SET SESSION sql_mode = ?', [$mode]);
        }
        foreach ([[], ['desde' => '2024-01-01'], ['usuario' => '0101'], ['desde' => '2025-01-01', 'hasta' => '2025-12-31']] as $filter) {
            self::assertSame($this->comparable($this->reference($filter)),
                $this->comparable((new MantencionEstadisticasService)->statisticsForFilters($filter)));
        }
    }

    public function test_get_entrypoint_uses_resolved_filters_and_empty_results_do_not_read_details(): void
    {
        $get = $_GET;
        $post = $_POST;
        try {
            $_POST = [];
            $_GET = ['desde' => '2026-09-03', 'hasta' => '2026-09-01', 'usuario' => '101'];
            $service = new MantencionEstadisticasService;
            $filters = $service->resolveFilters([], $_GET);
            self::assertSame($this->comparable($this->reference($filters)), $this->comparable($service->handle()));
        } finally {
            $_GET = $get;
            $_POST = $post;
        }
        DB::flushQueryLog();
        DB::enableQueryLog();
        $actual = (new MantencionEstadisticasService)->statisticsForFilters(['usuario' => 'missing']);
        $queries = DB::getQueryLog();
        DB::disableQueryLog();
        self::assertSame(0, $actual['total']);
        $reads = array_filter($queries, fn ($q) => str_contains($q['query'], 'from `redmine_mantencion_reportes`'));
        self::assertCount(3, $reads);
        foreach ($reads as $query) {
            self::assertStringNotContainsString('`r`.*', $query['query']);
            self::assertStringNotContainsString('descripcion', $query['query']);
            self::assertStringNotContainsString('asunto', $query['query']);
        }
    }

    public function test_unfiltered_statistics_keep_the_full_reader_without_extra_metadata_queries(): void
    {
        $expected = $this->comparable($this->reference([]));
        DB::flushQueryLog();
        DB::enableQueryLog();
        self::assertSame($expected, $this->comparable((new MantencionEstadisticasService)->statisticsForFilters([])));
        $queries = DB::getQueryLog();
        DB::disableQueryLog();
        $reads = array_filter($queries, fn ($q) => str_contains($q['query'], 'from `redmine_mantencion_reportes`'));
        self::assertCount(3, $reads);
        foreach ($reads as $query) {
            self::assertStringContainsString('`r`.*', $query['query']);
        }
    }

    public function test_filtered_statistics_fall_back_when_the_detail_read_fails(): void
    {
        $filters = ['desde' => '2026-09-01', 'hasta' => '2026-09-03'];
        $expected = $this->comparable($this->reference($filters));
        self::assertGreaterThan(0, $expected['total']);

        $dispatcher = new Dispatcher(app());
        DB::connection()->setEventDispatcher($dispatcher);
        $failed = false;
        $dispatcher->listen(QueryExecuted::class, function (QueryExecuted $event) use (&$failed): void {
            if (! $failed && str_contains($event->sql, '`redmine_mantencion_reportes`')
                && str_contains($event->sql, '`r`.*') && str_contains($event->sql, 'id IN (')) {
                $failed = true;
                throw new \RuntimeException('Synthetic statistics detail read failure');
            }
        });
        try {
            self::assertSame($expected, $this->comparable((new MantencionEstadisticasService)->statisticsForFilters($filters)));
            self::assertTrue($failed);
        } finally {
            DB::connection()->unsetEventDispatcher();
        }
    }

    public function test_large_reports_outside_the_range_do_not_transfer_their_text(): void
    {
        $seed = (array) DB::table('redmine_mantencion_reportes')->where('id', 7)->first();
        for ($batch = 0; $batch < 4; $batch++) {
            $reports = $links = [];
            for ($i = 1; $i <= 100; $i++) {
                $id = 1000 + $batch * 100 + $i;
                $reports[] = array_replace($seed, ['id' => $id, 'fuente' => 'manual', 'fuente_id' => 'large-'.$id,
                    'estado' => $i % 2 ? 'archivado' : 'pendiente', 'fecha_reporte' => '2023-01-01',
                    'asunto' => str_repeat('Asunto ', 1000), 'descripcion' => str_repeat('Detalle largo. ', 3000)]);
                foreach ([1, 2, 3] as $group) {
                    $links[] = ['grupo_id' => $group, 'origen' => 'mantencion', 'reporte_id' => $id];
                }
            }
            DB::table('redmine_mantencion_reportes')->insert($reports);
            DB::table('horas_extra_grupo_reportes')->insert($links);
        }
        unset($reports, $links, $seed);
        $filter = ['desde' => '2026-09-01', 'hasta' => '2026-09-03'];
        $measure = function (callable $read): array {
            gc_collect_cycles();
            memory_reset_peak_usage();
            $memory = memory_get_usage();
            $start = hrtime(true);
            $value = $read();

            return [$value, ['elapsed_ms' => round((hrtime(true) - $start) / 1e6, 3), 'peak_bytes' => memory_get_peak_usage() - $memory]];
        };
        $this->reference($filter);
        (new MantencionEstadisticasService)->statisticsForFilters($filter);
        [$expected, $before] = $measure(fn () => $this->reference($filter));
        [$actual, $after] = $measure(fn () => (new MantencionEstadisticasService)->statisticsForFilters($filter));
        self::assertSame($this->comparable($expected), $this->comparable($actual));
        self::assertLessThan($before['peak_bytes'] / 4, $after['peak_bytes']);
        file_put_contents(sys_get_temp_dir().'/nova-p06-mantencion-statistics-metrics.json', json_encode(compact('before', 'after')), LOCK_EX);
    }

    public function test_concurrent_changes_do_not_mix_metadata_and_details_in_the_read_transaction(): void
    {
        $filters = ['desde' => '2020-01-01'];
        $expected = $this->comparable($this->reference($filters));
        $dispatcher = new Dispatcher;
        DB::connection()->setEventDispatcher($dispatcher);
        $changed = false;
        $dispatcher->listen(QueryExecuted::class, function ($event) use (&$changed): void {
            if (! $changed && str_starts_with($event->sql, 'select `r`.`id`, `r`.`fuente`')) {
                $changed = true;
                DB::connection('concurrent')->table('redmine_mantencion_reportes')->where('id', 7)->update([
                    'descripcion' => 'Cambio concurrente', 'id_redmine_asignado' => 'new-owner', 'asignado_nombre' => 'Nueva persona',
                ]);
            }
        });
        try {
            self::assertSame($expected, $this->comparable((new MantencionEstadisticasService)->statisticsForFilters($filters)));
            self::assertTrue($changed);
        } finally {
            DB::connection()->unsetEventDispatcher();
        }
        self::assertSame($this->comparable($this->reference($filters)), $this->comparable((new MantencionEstadisticasService)->statisticsForFilters($filters)));
    }
}
